/*
 * generated by Xtext 2.10.0
 */
package it.cnr.istc.keen.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class DdlWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public DdlWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
