/*
 * generated by Xtext 2.10.0
 */
package it.cnr.istc.keen.tests

import com.google.inject.Inject
import it.cnr.istc.keen.ddl.Ddl
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DdlInjectorProvider)
class DdlParsingTest{

	@Inject
	ParseHelper<Ddl> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
