/*
 * generated by Xtext 2.10.0
 */
package it.cnr.istc.keen


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DdlStandaloneSetup extends DdlStandaloneSetupGenerated {

	def static void doSetup() {
		new DdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
